/*
 * Filename: swc_clock.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component Clock that displays time as hour and minute 
 * name: swc_Clock
 * shortname: Clock
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_clock.h"



/* USER CODE START SWC_CLOCK_INCLUDE */
#include "stdlib.h"
/* USER CODE END SWC_CLOCK_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CLOCK_USERDEFINITIONS */
#include "clock.h"
/* USER CODE END SWC_CLOCK_USERDEFINITIONS */



/*
 * component: swc_Clock
 * cycletime: 50
 * description: Runnable
 * events: 
 * name: CLOCK_input_run
 * shortname: input
 * signalIN: 
 * signalOUT: so_inputevent
 * task: tsk_input
 */
void CLOCK_input_run(RTE_event ev){
	
	/* USER CODE START CLOCK_input_run */
    
//    UART_LOG_PutString("i am in input runnable");
    
    RTE_SC_INPUT_pullPort(&SO_INPUTEVENT_signal);
    
//    SC_INPUT_data_t event;
//    event = RTE_SC_INPUT_get(&SO_INPUTEVENT_signal);
//    char buffer[100];
//    itoa(event.m_ev, buffer, 10);
//    UART_LOG_PutString(buffer);
    
    /* USER CODE END CLOCK_input_run */
}

/*
 * component: swc_Clock
 * cycletime: 0
 * description: Runnable
 * events: ev_event_onData
 * name: CLOCK_control_run
 * shortname: control
 * signalIN: so_inputevent
 * signalOUT: so_control
 * task: tsk_control
 */
void CLOCK_control_run(RTE_event ev){
	
	/* USER CODE START CLOCK_control_run */
    
//    UART_LOG_PutString("i am in control runnable");
//    char buffer[100];
    
    SC_INPUT_data_t rxinput;
    
    rxinput = RTE_SC_INPUT_get(&SO_INPUTEVENT_signal);
    
    if(rxinput.m_ev == EV_KEYLEFT)
    {
//        UART_LOG_PutString("KeyLeft Pressed\n");
//        itoa(rxinput.m_state, buffer, 10);
//        UART_LOG_PutString(buffer);

        ProcessEvent(rxinput.m_ev);
    }
    else if(rxinput.m_ev == EV_KEYRIGHT)
    {
//        UART_LOG_PutString("KeyRight Pressed\n");
//        itoa(rxinput.m_ev, buffer, 10);
//        UART_LOG_PutString(buffer);
        
        ProcessEvent(rxinput.m_ev);
    }
    else if(rxinput.m_ev == EV_KEYRIGHTLONGPRESS)
    {
//        UART_LOG_PutString("KeyRight Pressed Long.........\n");
//        itoa(rxinput.m_ev, buffer, 10);
//        UART_LOG_PutString(buffer);
        
        ProcessEvent(rxinput.m_ev);
    }
    else if(rxinput.m_ev    ==  EV_1MIN)
    {
//        UART_LOG_PutString("One minute event fired\n");
        
        ProcessEvent(rxinput.m_ev);
    }
    else if(rxinput.m_ev    ==  EV_250MS)
    {
//        UART_LOG_PutString("250ms event fired\n");
        
        ProcessEvent(rxinput.m_ev);
    }
    
    /* USER CODE END CLOCK_control_run */
}

/*
 * component: swc_Clock
 * cycletime: 250
 * description: Runnable
 * events: 
 * name: CLOCK_display_run
 * shortname: display
 * signalIN: so_control
 * signalOUT: so_displayonTFT
 * task: tsk_input
 */
void CLOCK_display_run(RTE_event ev){
	
	/* USER CODE START CLOCK_display_run */

    SC_DISPLAY_data_t    tft_config  =   SC_DISPLAY_INIT_DATA;
    
    SC_CONTROL_data_t   control_data    = SC_CONTROL_INIT_DATA;
    
    control_data    =   RTE_SC_CONTROL_get(&SO_CONTROL_signal);
    
    tft_config.hour     =   control_data.hour;
    tft_config.minute   =   control_data.minute;
    
    RTE_SC_DISPLAY_set(&SO_DISPLAYONTFT_signal, tft_config);
    RTE_SC_DISPLAY_pushPort(&SO_DISPLAYONTFT_signal);
    
    /* USER CODE END CLOCK_display_run */
}

/* USER CODE START SWC_CLOCK_FUNCTIONS */

/* USER CODE END SWC_CLOCK_FUNCTIONS */

